In [1]:
import tensorflow as tf

In [2]:
x = tf.constant(4, shape=(1, 1), dtype=tf.float32)

In [3]:
x

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[4.]], dtype=float32)>

In [4]:
x = tf.constant([[1, 2, 3], [4, 5, 6]], shape=(2, 3))
print(x)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [5]:
x = tf.eye(3)
print(x)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [6]:
x = tf.ones((4, 3))
print(x)


tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(4, 3), dtype=float32)


In [7]:
x = tf.zeros((3, 2, 5))
print(x)

tf.Tensor(
[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]], shape=(3, 2, 5), dtype=float32)


In [8]:
x = tf.random.uniform((2, 2), minval=0, maxval=1)
print(x)

tf.Tensor(
[[0.3222289  0.05490816]
 [0.43368614 0.09641862]], shape=(2, 2), dtype=float32)


In [9]:
x = tf.random.normal((3, 3), mean=0, stddev=1)
print(tf.cast(x, dtype=tf.float64))

tf.Tensor(
[[ 0.7973401  -0.05203833  0.57729161]
 [ 0.31057695 -1.30291224 -2.54300642]
 [-0.63794887 -0.34534162 -0.61960107]], shape=(3, 3), dtype=float64)


In [10]:
x = tf.range(9)
x = tf.range(start=0, limit=10, delta=2)
print(x)

tf.Tensor([0 2 4 6 8], shape=(5,), dtype=int32)


In [11]:
# Math
x = tf.constant([1, 2, 3])
y = tf.constant([9, 8, 7])

z = tf.add(x, y)
z = x + y

z = tf.subtract(x, y)
z = x - y

z = tf.divide(x, y)
z = x / y

z = tf.multiply(x, y)
z = x * y

z = tf.tensordot(x, y, axes=1)

z = x ** 5

x = tf.random.normal((2, 3))
y = tf.random.normal((3, 2))
z = tf.matmul(x, y)
z = x @ y

x = tf.random.normal((2, 2))
